const movieExampleCards = [
  {
    id: 1,
    name: "33 слова о дизайне",
    duration: 107,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: true,
  },
  {
    id: 2,
    name: "Киноальманах «100 лет дизайна»",
    duration: 63,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: false,
  },
  {
    id: 3,
    name: "В погоне за Бенкси",
    duration: 102,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: false,
  },
  {
    id: 4,
    name: "Баския: Взрыв реальности",
    duration: 81,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: false,
  },
  {
    id: 5,
    name: "Бег это свобода",
    duration: 104,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: false,
  },
  {
    id: 6,
    name: "Книготорговцы",
    duration: 97,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: false,
  },
  {
    id: 7,
    name: "Когда я думаю о Германии ночью",
    duration: 116,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: false,
  },
  {
    id: 8,
    name: "Gimme Danger: История Игги и The Stooges",
    duration: 119,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: false,
  },
  {
    id: 9,
    name: "Дженис: Маленькая девочка грустит",
    duration: 102,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: true,
  },
  {
    id: 10,
    name: "Соберись перед прыжком",
    duration: 70,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: true,
  },
  {
    id: 11,
    name: "Пи Джей Харви: A dog called money",
    duration: 64,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: false,
  },
  {
    id: 12,
    name: "По волнам: Искусство звука в кино",
    duration: 67,
    image: "https://pbs.twimg.com/media/D20ZVyYXgAAhiRL.jpg:large",
    isSaved: false,
  },
];

export default movieExampleCards;
